services:
  ffc-pay-responses:
    build:
      context: .
      target: production
    image: ffc-pay-responses
    container_name: ffc-pay-responses
    depends_on:
      - ffc-pay-responses-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-responses-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      PAYMENTSUBMIT_TOPIC_ADDRESS: ${PAYMENTSUBMIT_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      PAYMENTSUBMIT_SUBSCRIPTION_ADDRESS: ${PAYMENTSUBMIT_SUBSCRIPTION_ADDRESS:-ffc-pay-responses}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGEMENT_TOPIC_ADDRESS: ${ACKNOWLEDGEMENT_TOPIC_ADDRESS:-ffc-pay-acknowledgement}${MESSAGE_QUEUE_SUFFIX}
      RETURN_TOPIC_ADDRESS: ${RETURN_TOPIC_ADDRESS:-ffc-pay-return}${MESSAGE_QUEUE_SUFFIX}
      EVENT_TOPIC_ADDRESS: ${EVENT_TOPIC_ADDRESS:-ffc-pay-event}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-ffc-pay-events}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      POSTGRES_DB: ffc_pay_responses
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-responses-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-pay-responses-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_responses
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  ffc-pay-responses-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.32.0
    command: "azurite-blob --skipApiVersionCheck --loose --blobHost 0.0.0.0"
